server:
  port: 8888
spring:
  application:
    name: server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/soulchild81/soulchild_config.git
          username: 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
          password: ""
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true