server:
  port: 8888
spring:
  application:
    name: server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/soulchild81/soulchild_config.git
          username: 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
          password: ""